using Microsoft.EntityFrameworkCore.Migrations;

namespace HaloBiz.Migrations
{
    public partial class addsLGASeedData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql("SET IDENTITY_INSERT LGAs ON"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (1, 1, 'Aba North')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (2, 1, 'Aba South')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (3, 1, 'Arochukwu')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (4, 1, 'Bende')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (5, 1, 'Ikwuano')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (6, 1, 'Isiala Ngwa North')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (7, 1, 'Isiala Ngwa South')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (8, 1, 'Isuikwuato')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (9, 1, 'Obi Ngwa')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (10, 1, 'Ohafia')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (11, 1, 'Osisioma')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (12, 1, 'Ugwunagbo')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (13, 1, 'Ukwa East')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (14, 1, 'Ukwa West')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (15, 1, 'Umuahia North')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (16, 1, 'Umuahia South')"); 
             migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (17, 1, 'Umu Nneochi')"); 

            
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(18, 2, 'Demsa')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(19, 2, 'Fufure')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(20, 2, 'Ganye')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(21, 2, 'Gayuk')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(22, 2, 'Gombi')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(23, 2, 'Grie')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(24, 2, 'Hong')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(25, 2, 'Jada')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(26, 2, 'Larmurde')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(27, 2, 'Madagali')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(28, 2, 'Maiha')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(29, 2, 'Mayo Belwa')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(30, 2, 'Michika')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(31, 2, 'Mubi North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(32, 2, 'Mubi South')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(33, 2, 'Numan')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(34, 2, 'Shelleng')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(35, 2, 'Song')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(36, 2, 'Toungo')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(37, 2, 'Yola North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(38, 2, 'Yola South')"); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (39, 3, 'Abak')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (40, 3, 'Eastern Obolo')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (41, 3, 'Eket')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (42, 3, 'Esit Eket')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (43, 3, 'Essien Udim')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (44, 3, 'Etim Ekpo')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (45, 3, 'Etinan')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (46, 3, 'Ibeno')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (47, 3, 'Ibesikpo Asutan')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (48, 3, 'Ibiono-Ibom')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (49, 3, 'Ika')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (50, 3, 'Ikono')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (51, 3, 'Ikot Abasi')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (52, 3, 'Ikot Ekpene')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (53, 3, 'Ini')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (54, 3, 'Itu')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (55, 3, 'Mbo')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (56, 3, 'Mkpat-Enin')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (57, 3, 'Nsit-Atai')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (58, 3, 'Nsit-Ibom')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (59, 3, 'Nsit-Ubium')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (60, 3, 'Obot Akara')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (61, 3, 'Okobo')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (62, 3, 'Onna')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (63, 3, 'Oron')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (64, 3, 'Oruk Anam')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (65, 3, 'Udung-Uko')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (66, 3, 'Ukanafun')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (67, 3, 'Uruan')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (68, 3, 'Urue-Offong/Oruko')  "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES (69, 3, 'Uyo')  "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(70, 4, 'Aguata')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(71, 4, 'Anambra East')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(72, 4, 'Anambra West')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(73, 4, 'Anaocha')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(74, 4, 'Awka North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(75, 4, 'Awka South')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(76, 4, 'Ayamelum')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(77, 4, 'Dunukofia')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(78, 4, 'Ekwusigo')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(79, 4, 'Idemili North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(80, 4, 'Idemili South')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(81, 4, 'Ihiala')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(82, 4, 'Njikoka')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(83, 4, 'Nnewi North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(84, 4, 'Nnewi South')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(85, 4, 'Ogbaru')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(86, 4, 'Onitsha North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(87, 4, 'Onitsha South')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(88, 4, 'Orumba North')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(89, 4, 'Orumba South')"); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(90, 4, 'Oyi')"); 


            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(91, 5, 'Alkaleri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(92, 5, 'Bauchi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(93, 5, 'Bogoro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(94, 5, 'Damban') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(95, 5, 'Darazo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(96, 5, 'Dass') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(97, 5, 'Gamawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(98, 5, 'Ganjuwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(99, 5, 'Giade') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(100, 5, 'Itas/Gadau') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(101, 5, 'Jamaare') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(102, 5, 'Katagum') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(103, 5, 'Kirfi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(104, 5, 'Misau') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(105, 5, 'Ningi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(106, 5, 'Shira') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(107, 5, 'Tafawa Balewa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(108, 5, 'Toro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(109, 5, 'Warji') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(110, 5, 'Zaki') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(111, 6, 'Brass') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(112, 6, 'Ekeremor') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(113, 6, 'Kolokuma/Opokuma') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(114, 6, 'Nembe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(115, 6, 'Ogbia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(116, 6, 'Sagbama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(117, 6, 'Southern Ijaw') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(118, 6, 'Yenagoa') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(119, 7, 'Agatu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(120, 7, 'Apa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(121, 7, 'Ado') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(122, 7, 'Buruku') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(123, 7, 'Gboko') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(124, 7, 'Guma') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(125, 7, 'Gwer East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(126, 7, 'Gwer West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(127, 7, 'Katsina-Ala') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(128, 7, 'Konshisha') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(129, 7, 'Kwande') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(130, 7, 'Logo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(131, 7, 'Makurdi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(132, 7, 'Obi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(133, 7, 'Ogbadibo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(134, 7, 'Ohimini') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(135, 7, 'Oju') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(136, 7, 'Okpokwu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(137, 7, 'Oturkpo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(138, 7, 'Tarka') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(139, 7, 'Ukum') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(140, 7, 'Ushongo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(141, 7, 'Vandeikya') "); 


            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(142, 8, 'Abadam') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(143, 8, 'Askira/Uba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(144, 8, 'Bama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(145, 8, 'Bayo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(146, 8, 'Biu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(147, 8, 'Chibok') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(148, 8, 'Damboa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(149, 8, 'Dikwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(150, 8, 'Gubio') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(151, 8, 'Guzamala') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(152, 8, 'Gwoza') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(153, 8, 'Hawul') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(154, 8, 'Jere') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(155, 8, 'Kaga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(156, 8, 'Kala/Balge') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(157, 8, 'Konduga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(158, 8, 'Kukawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(159, 8, 'Kwaya Kusar') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(160, 8, 'Mafa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(161, 8, 'Magumeri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(162, 8, 'Maiduguri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(163, 8, 'Marte') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(164, 8, 'Mobbar') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(165, 8, 'Monguno') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(166, 8, 'Ngala') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(167, 8, 'Nganzai') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(168, 8, 'Shani') "); 
            
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(169, 9, 'Abi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(170, 9, 'Akamkpa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(171, 9, 'Akpabuyo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(172, 9, 'Bakassi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(173, 9, 'Bekwarra') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(174, 9, 'Biase') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(175, 9, 'Boki') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(176, 9, 'Calabar Municipal') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(177, 9, 'Calabar South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(178, 9, 'Etung') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(179, 9, 'Ikom') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(180, 9, 'Obanliku') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(181, 9, 'Obubra') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(182, 9, 'Obudu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(183, 9, 'Odukpani') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(184, 9, 'Ogoja') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(185, 9, 'Yakuur') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(186, 9, 'Yala') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(187, 10, 'Aniocha North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(188, 10, 'Aniocha South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(189, 10, 'Bomadi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(190, 10, 'Burutu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(191, 10, 'Ethiope East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(192, 10, 'Ethiope West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(193, 10, 'Ika North East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(194, 10, 'Ika South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(195, 10, 'Isoko North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(196, 10, 'Isoko South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(197, 10, 'Ndokwa East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(198, 10, 'Ndokwa West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(199, 10, 'Okpe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(200, 10, 'Oshimili North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(201, 10, 'Oshimili South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(202, 10, 'Patani') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(203, 10, 'Sapele') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(204, 10, 'Udu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(205, 10, 'Ughelli North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(206, 10, 'Ughelli South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(207, 10, 'Ukwuani') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(208, 10, 'Uvwie') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(209, 10, 'Warri North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(210, 10, 'Warri South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(211, 10, 'Warri South West') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(212, 11, 'Abakaliki') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(213, 11, 'Afikpo North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(214, 11, 'Afikpo South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(215, 11, 'Ebonyi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(216, 11, 'Ezza North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(217, 11, 'Ezza South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(218, 11, 'Ikwo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(219, 11, 'Ishielu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(220, 11, 'Ivo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(221, 11, 'Izzi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(222, 11, 'Ohaozara') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(223, 11, 'Ohaukwu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(224, 11, 'Onicha') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(225, 12, 'Akoko-Edo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(226, 12, 'Egor') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(227, 12, 'Esan Central') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(228, 12, 'Esan North-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(229, 12, 'Esan South-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(230, 12, 'Esan West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(231, 12, 'Etsako Central') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(232, 12, 'Etsako East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(233, 12, 'Etsako West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(234, 12, 'Igueben') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(235, 12, 'Ikpoba Okha') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(236, 12, 'Orhionmwon') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(237, 12, 'Oredo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(238, 12, 'Ovia North-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(239, 12, 'Ovia South-West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(240, 12, 'Owan East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(241, 12, 'Owan West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(242, 12, 'Uhunmwonde') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(243, 13, 'Ado Ekiti') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(244, 13, 'Efon') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(245, 13, 'Ekiti East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(246, 13, 'Ekiti South-West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(247, 13, 'Ekiti West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(248, 13, 'Emure') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(249, 13, 'Gbonyin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(250, 13, 'Ido Osi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(251, 13, 'Ijero') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(252, 13, 'Ikere') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(253, 13, 'Ikole') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(254, 13, 'Ilejemeje') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(255, 13, 'Irepodun/Ifelodun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(256, 13, 'Ise/Orun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(257, 13, 'Moba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(258, 13, 'Oye') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(259, 14, 'Aninri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(260, 14, 'Awgu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(261, 14, 'Enugu East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(262, 14, 'Enugu North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(263, 14, 'Enugu South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(264, 14, 'Ezeagu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(265, 14, 'Igbo Etiti') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(266, 14, 'Igbo Eze North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(267, 14, 'Igbo Eze South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(268, 14, 'Isi Uzo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(269, 14, 'Nkanu East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(270, 14, 'Nkanu West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(271, 14, 'Nsukka') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(272, 14, 'Oji River') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(273, 14, 'Udenu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(274, 14, 'Udi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(275, 14, 'Uzo Uwani') "); 
            
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(276, 15, 'Abaji') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(277, 15, 'Bwari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(278, 15, 'Gwagwalada') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(279, 15, 'Kuje') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(280, 15, 'Kwali') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(281, 15, 'Municipal Area Council') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(282, 16, 'Akko') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(283, 16, 'Balanga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(284, 16, 'Billiri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(285, 16, 'Dukku') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(286, 16, 'Funakaye') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(287, 16, 'Gombe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(288, 16, 'Kaltungo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(289, 16, 'Kwami') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(290, 16, 'Nafada') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(291, 16, 'Shongom') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(292, 16, 'Yamaltu/Deba') "); 


            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(293, 17, 'Aboh Mbaise') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(294, 17, 'Ahiazu Mbaise') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(295, 17, 'Ehime Mbano') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(296, 17, 'Ezinihitte') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(297, 17, 'Ideato North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(298, 17, 'Ideato South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(299, 17, 'Ihitte/Uboma') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(300, 17, 'Ikeduru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(301, 17, 'Isiala Mbano') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(302, 17, 'Isu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(303, 17, 'Mbaitoli') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(304, 17, 'Ngor Okpala') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(305, 17, 'Njaba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(306, 17, 'Nkwerre') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(307, 17, 'Nwangele') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(308, 17, 'Obowo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(309, 17, 'Oguta') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(310, 17, 'Ohaji/Egbema') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(311, 17, 'Okigwe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(312, 17, 'Orlu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(313, 17, 'Orsu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(314, 17, 'Oru East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(315, 17, 'Oru West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(316, 17, 'Owerri Municipal') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(317, 17, 'Owerri North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(318, 17, 'Owerri West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(319, 17, 'Unuimo') "); 


            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(320, 18, 'Auyo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(321, 18, 'Babura') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(322, 18, 'Biriniwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(323, 18, 'Birnin Kudu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(324, 18, 'Buji') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(325, 18, 'Dutse') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(326, 18, 'Gagarawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(327, 18, 'Garki') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(328, 18, 'Gumel') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(329, 18, 'Guri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(330, 18, 'Gwaram') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(331, 18, 'Gwiwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(332, 18, 'Hadejia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(333, 18, 'Jahun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(334, 18, 'Kafin Hausa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(335, 18, 'Kazaure') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(336, 18, 'Kiri Kasama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(337, 18, 'Kiyawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(338, 18, 'Kaugama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(339, 18, 'Maigatari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(340, 18, 'Malam Madori') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(341, 18, 'Miga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(342, 18, 'Ringim') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(343, 18, 'Roni') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(344, 18, 'Sule Tankarkar') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(345, 18, 'Taura') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(346, 18, 'Yankwashi') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(347, 19, 'Birnin Gwari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(348, 19, 'Chikun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(349, 19, 'Giwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(350, 19, 'Igabi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(351, 19, 'Ikara') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(352, 19, 'Jaba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(353, 19, 'Jemaa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(354, 19, 'Kachia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(355, 19, 'Kaduna North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(356, 19, 'Kaduna South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(357, 19, 'Kagarko') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(358, 19, 'Kajuru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(359, 19, 'Kaura') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(360, 19, 'Kauru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(361, 19, 'Kubau') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(362, 19, 'Kudan') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(363, 19, 'Lere') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(364, 19, 'Makarfi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(365, 19, 'Sabon Gari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(366, 19, 'Sanga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(367, 19, 'Soba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(368, 19, 'Zangon Kataf') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(369, 19, 'Zaria') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(370, 20, 'Ajingi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(371, 20, 'Albasu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(372, 20, 'Bagwai') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(373, 20, 'Bebeji') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(374, 20, 'Bichi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(375, 20, 'Bunkure') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(376, 20, 'Dala') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(377, 20, 'Dambatta') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(378, 20, 'Dawakin Kudu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(379, 20, 'Dawakin Tofa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(380, 20, 'Doguwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(381, 20, 'Fagge') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(382, 20, 'Gabasawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(383, 20, 'Garko') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(384, 20, 'Garun Mallam') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(385, 20, 'Gaya') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(386, 20, 'Gezawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(387, 20, 'Gwale') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(388, 20, 'Gwarzo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(389, 20, 'Kabo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(390, 20, 'Kano Municipal') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(391, 20, 'Karaye') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(392, 20, 'Kibiya') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(393, 20, 'Kiru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(394, 20, 'Kumbotso') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(395, 20, 'Kunchi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(396, 20, 'Kura') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(397, 20, 'Madobi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(398, 20, 'Makoda') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(399, 20, 'Minjibir') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(400, 20, 'Nasarawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(401, 20, 'Rano') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(402, 20, 'Rimin Gado') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(403, 20, 'Rogo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(404, 20, 'Shanono') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(405, 20, 'Sumaila') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(406, 20, 'Takai') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(407, 20, 'Tarauni') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(408, 20, 'Tofa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(409, 20, 'Tsanyawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(410, 20, 'Tudun Wada') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(411, 20, 'Ungogo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(412, 20, 'Warawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(413, 20, 'Wudil') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(414, 21, 'Bakori') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(415, 21, 'Batagarawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(416, 21, 'Batsari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(417, 21, 'Baure') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(418, 21, 'Bindawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(419, 21, 'Charanchi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(420, 21, 'Dandume') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(421, 21, 'Danja') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(422, 21, 'Dan Musa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(423, 21, 'Daura') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(424, 21, 'Dutsi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(425, 21, 'Dutsin Ma') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(426, 21, 'Faskari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(427, 21, 'Funtua') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(428, 21, 'Ingawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(429, 21, 'Jibia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(430, 21, 'Kafur') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(431, 21, 'Kaita') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(432, 21, 'Kankara') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(433, 21, 'Kankia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(434, 21, 'Katsina') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(435, 21, 'Kurfi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(436, 21, 'Kusada') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(437, 21, 'MaiAdua') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(438, 21, 'Malumfashi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(439, 21, 'Mani') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(440, 21, 'Mashi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(441, 21, 'Matazu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(442, 21, 'Musawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(443, 21, 'Rimi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(444, 21, 'Sabuwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(445, 21, 'Safana') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(446, 21, 'Sandamu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(447, 21, 'Zango') "); 
            
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(448, 22, 'Aleiro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(449, 22, 'Arewa Dandi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(450, 22, 'Argungu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(451, 22, 'Augie') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(452, 22, 'Bagudo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(453, 22, 'Birnin Kebbi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(454, 22, 'Bunza') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(455, 22, 'Dandi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(456, 22, 'Fakai') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(457, 22, 'Gwandu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(458, 22, 'Jega') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(459, 22, 'Kalgo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(460, 22, 'Koko Besse') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(461, 22, 'Maiyama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(462, 22, 'Ngaski') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(463, 22, 'Sakaba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(464, 22, 'Shanga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(465, 22, 'Suru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(466, 22, 'Wasagu Danko') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(467, 22, 'Yauri') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(468, 22, 'Zuru') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(469, 23, 'Adavi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(470, 23, 'Ajaokuta') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(471, 23, 'Ankpa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(472, 23, 'Bassa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(473, 23, 'Dekina') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(474, 23, 'Ibaji') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(475, 23, 'Idah') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(476, 23, 'Igalamela Odolu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(477, 23, 'Ijumu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(478, 23, 'Kabba/Bunu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(479, 23, 'Kogi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(480, 23, 'Lokoja') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(481, 23, 'Mopa Muro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(482, 23, 'Ofu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(483, 23, 'Ogori Magongo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(484, 23, 'Okehi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(485, 23, 'Okene') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(486, 23, 'Olamaboro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(487, 23, 'Omala') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(488, 23, 'Yagba East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(489, 23, 'Yagba West') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(490, 24, 'Asa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(491, 24, 'Baruten') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(492, 24, 'Edu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(493, 24, 'Ekiti') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(494, 24, 'Ifelodun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(495, 24, 'Ilorin East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(496, 24, 'Ilorin South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(497, 24, 'Ilorin West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(498, 24, 'Irepodun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(499, 24, 'Isin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(500, 24, 'Kaiama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(501, 24, 'Moro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(502, 24, 'Offa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(503, 24, 'Oke Ero') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(504, 24, 'Oyun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(505, 24, 'Pategi') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(506, 25, 'Agege') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(507, 25, 'Ajeromi-Ifelodun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(508, 25, 'Alimosho') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(509, 25, 'Amuwo-Odofin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(510, 25, 'Apapa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(511, 25, 'Badagry') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(512, 25, 'Epe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(513, 25, 'Eti Osa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(514, 25, 'Ibeju-Lekki') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(515, 25, 'Ifako-Ijaiye') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(516, 25, 'Ikeja') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(517, 25, 'Ikorodu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(518, 25, 'Kosofe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(519, 25, 'Lagos Island') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(520, 25, 'Lagos Mainland') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(521, 25, 'Mushin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(522, 25, 'Ojo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(523, 25, 'Oshodi-Isolo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(524, 25, 'Shomolu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(525, 25, 'Surulere') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(526, 26, 'Akwanga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(527, 26, 'Awe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(528, 26, 'Doma') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(529, 26, 'Karu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(530, 26, 'Keana') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(531, 26, 'Keffi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(532, 26, 'Kokona') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(533, 26, 'Lafia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(534, 26, 'Nasarawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(535, 26, 'Nasarawa Egon') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(536, 26, 'Obi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(537, 26, 'Toto') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(538, 26, 'Wamba') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(539, 27, 'Agaie') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(540, 27, 'Agwara') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(541, 27, 'Bida') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(542, 27, 'Borgu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(543, 27, 'Bosso') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(544, 27, 'Chanchaga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(545, 27, 'Edati') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(546, 27, 'Gbako') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(547, 27, 'Gurara') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(548, 27, 'Katcha') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(549, 27, 'Kontagora') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(550, 27, 'Lapai') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(551, 27, 'Lavun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(552, 27, 'Magama') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(553, 27, 'Mariga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(554, 27, 'Mashegu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(555, 27, 'Mokwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(556, 27, 'Moya') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(557, 27, 'Paikoro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(558, 27, 'Rafi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(559, 27, 'Rijau') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(560, 27, 'Shiroro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(561, 27, 'Suleja') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(562, 27, 'Tafa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(563, 27, 'Wushishi') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(564, 28, 'Abeokuta North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(565, 28, 'Abeokuta South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(566, 28, 'Ado-Odo/Ota') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(567, 28, 'Egbado North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(568, 28, 'Egbado South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(569, 28, 'Ewekoro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(570, 28, 'Ifo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(571, 28, 'Ijebu East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(572, 28, 'Ijebu North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(573, 28, 'Ijebu North East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(574, 28, 'Ijebu Ode') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(575, 28, 'Ikenne') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(576, 28, 'Imeko Afon') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(577, 28, 'Ipokia') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(578, 28, 'Obafemi Owode') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(579, 28, 'Odeda') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(580, 28, 'Odogbolu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(581, 28, 'Ogun Waterside') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(582, 28, 'Remo North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(583, 28, 'Shagamu') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(584, 29, 'Akoko North-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(585, 29, 'Akoko North-West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(586, 29, 'Akoko South-West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(587, 29, 'Akoko South-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(588, 29, 'Akure North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(589, 29, 'Akure South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(590, 29, 'Ese Odo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(591, 29, 'Idanre') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(592, 29, 'Ifedore') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(593, 29, 'Ilaje') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(594, 29, 'Ile Oluji/Okeigbo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(595, 29, 'Irele') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(596, 29, 'Odigbo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(597, 29, 'Okitipupa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(598, 29, 'Ondo East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(599, 29, 'Ondo West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(600, 29, 'Ose') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(601, 29, 'Owo') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(602, 30, 'Atakunmosa East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(603, 30, 'Atakunmosa West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(604, 30, 'Aiyedaade') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(605, 30, 'Aiyedire') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(606, 30, 'Boluwaduro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(607, 30, 'Boripe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(608, 30, 'Ede North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(609, 30, 'Ede South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(610, 30, 'Ife Central') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(611, 30, 'Ife East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(612, 30, 'Ife North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(613, 30, 'Ife South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(614, 30, 'Egbedore') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(615, 30, 'Ejigbo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(616, 30, 'Ifedayo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(617, 30, 'Ifelodun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(618, 30, 'Ila') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(619, 30, 'Ilesa East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(620, 30, 'Ilesa West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(621, 30, 'Irepodun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(622, 30, 'Irewole') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(623, 30, 'Isokan') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(624, 30, 'Iwo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(625, 30, 'Obokun') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(626, 30, 'Odo Otin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(627, 30, 'Ola Oluwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(628, 30, 'Olorunda') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(629, 30, 'Oriade') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(630, 30, 'Orolu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(631, 30, 'Osogbo') "); 
            
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(632, 31, 'Afijio') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(633, 31, 'Akinyele') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(634, 31, 'Atiba') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(635, 31, 'Atisbo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(636, 31, 'Egbeda') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(637, 31, 'Ibadan North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(638, 31, 'Ibadan North-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(639, 31, 'Ibadan North-West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(640, 31, 'Ibadan South-East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(641, 31, 'Ibadan South-West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(642, 31, 'Ibarapa Central') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(643, 31, 'Ibarapa East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(644, 31, 'Ibarapa North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(645, 31, 'Ido') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(646, 31, 'Irepo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(647, 31, 'Iseyin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(648, 31, 'Itesiwaju') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(649, 31, 'Iwajowa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(650, 31, 'Kajola') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(651, 31, 'Lagelu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(652, 31, 'Ogbomosho North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(653, 31, 'Ogbomosho South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(654, 31, 'Ogo Oluwa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(655, 31, 'Olorunsogo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(656, 31, 'Oluyole') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(657, 31, 'Ona Ara') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(658, 31, 'Orelope') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(659, 31, 'Ori Ire') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(660, 31, 'Oyo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(661, 31, 'Oyo East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(662, 31, 'Saki East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(663, 31, 'Saki West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(664, 31, 'Surulere') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(665, 32, 'Bokkos') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(666, 32, 'Barkin Ladi') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(667, 32, 'Bassa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(668, 32, 'Jos East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(669, 32, 'Jos North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(670, 32, 'Jos South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(671, 32, 'Kanam') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(672, 32, 'Kanke') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(673, 32, 'Langtang South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(674, 32, 'Langtang North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(675, 32, 'Mangu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(676, 32, 'Mikang') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(677, 32, 'Pankshin') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(678, 32, 'Quaan Pan') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(679, 32, 'Riyom') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(680, 32, 'Shendam') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(681, 32, 'Wase') ");

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(682, 33, 'Abua/Odual') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(683, 33, 'Ahoada East') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(684, 33, 'Ahoada West') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(685, 33, 'Akuku-Toru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(686, 33, 'Andoni') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(687, 33, 'Asari-Toru') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(688, 33, 'Bonny') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(689, 33, 'Degema') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(690, 33, 'Eleme') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(691, 33, 'Emuoha') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(692, 33, 'Etche') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(693, 33, 'Gokana') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(694, 33, 'Ikwerre') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(695, 33, 'Khana') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(696, 33, 'Obio/Akpor') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(697, 33, 'Ogba Egbema Ndoni') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(698, 33, 'Ogu Bolo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(699, 33, 'Okrika') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(700, 33, 'Omuma') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(701, 33, 'Opobo Nkoro') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(702, 33, 'Oyigbo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(703, 33, 'Port Harcourt') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(704, 33, 'Tai') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(705, 34, 'Binji') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(706, 34, 'Bodinga') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(707, 34, 'Dange Shuni') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(708, 34, 'Gada') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(709, 34, 'Goronyo') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(710, 34, 'Gudu') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(711, 34, 'Gwadabawa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(712, 34, 'Illela') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(713, 34, 'Isa') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(714, 34, 'Kebbe') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(715, 34, 'Kware') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(716, 34, 'Rabah') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(717, 34, 'Sabon Birni') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(718, 34, 'Shagari') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(719, 34, 'Silame') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(720, 34, 'Sokoto North') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(721, 34, 'Sokoto South') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(722, 34, 'Tambuwal') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(723, 34, 'Tangaza') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(724, 34, 'Tureta') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(725, 34, 'Wamako') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(726, 34, 'Wurno') "); 
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(727, 34, 'Yabo') "); 

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(728, 35, 'Ardo Kola') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(729, 35, 'Bali') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(730, 35, 'Donga') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(731, 35, 'Gashaka') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(732, 35, 'Gassol') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(733, 35, 'Ibi') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(734, 35, 'Jalingo') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(735, 35, 'Karim Lamido') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(736, 35, 'Kumi') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(737, 35, 'Lau') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(738, 35, 'Sardauna') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(739, 35, 'Takum') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(740, 35, 'Ussa') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(741, 35, 'Wukari') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(742, 35, 'Yorro') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(743, 35, 'Zing') ");

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(744, 36, 'Bade') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(745, 36, 'Bursari') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(746, 36, 'Damaturu') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(747, 36, 'Fika') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(748, 36, 'Fune') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(749, 36, 'Geidam') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(750, 36, 'Gujba') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(751, 36, 'Gulani') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(752, 36, 'Jakusko') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(753, 36, 'Karasuwa') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(754, 36, 'Machina') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(755, 36, 'Nangere') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(756, 36, 'Nguru') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(757, 36, 'Potiskum') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(758, 36, 'Tarmuwa') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(759, 36, 'Yunusari') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(760, 36, 'Yusufari') ");

            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(761, 37, 'Anka') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(762, 37, 'Bakura') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(763, 37, 'Birnin Magaji Kiyaw') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(764, 37, 'Bukkuyum') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(765, 37, 'Bungudu') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(766, 37, 'Gummi') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(767, 37, 'Gusau') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(768, 37, 'Kaura Namoda') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(769, 37, 'Maradun') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(770, 37, 'Maru') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(771, 37, 'Shinkafi') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(772, 37, 'Talata Mafara') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(773, 37, 'Chafe') ");
            migrationBuilder.Sql("INSERT INTO LGAs (Id, StateId, Name) VALUES(774, 37, 'Zurmi') ");


        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
